### ISSUE TITLE
Setup guide is a little too minimal, ERR_INVALID_ARG_TYPE, unset AUTH_KEY

### ISSUE THREAD

**Issue by sjoerdvanhoof** [Ewoodss/npo-dl#27]
Hi,

I have joined the WVkeys discord and got verified. However, when I try to set up the tool, I keep on getting an issue that the `challenge` variable in `generate_request()` within `getWvKeys class` is `undefined`. Can you add a bit more information on how to set it all up?

**Comment by sjoerdvanhoof** [comment]
Here is my error:

```
node:buffer:324
  throw new ERR_INVALID_ARG_TYPE(
        ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at Function.from (node:buffer:324:9)
    at getWvKeys.generate_request (file:///Users/GitRepos/npo-dl/getwvkeys.js:54:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async getWvKeys (file:///Users/GitRepos/npo-dl/getwvkeys.js:110:27) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by sjoerdvanhoof** [comment]
I have found the solution. The `AUTH_KEY` is found as `API key` under Profile on the WVkeys website.

**Comment by Ewoodss** [comment]
Yeah the documentation is still a bit lacking, originally i was planning on creating this as a cli tool, but i haven't got around to-do that.

**Comment by RezzZ** [comment]
perhaps instead of a client tool (which could be platform bound), you can look into [this project](https://github.com/Tzahi12345/YoutubeDL-Material) that also uses yt-dlp to download from youtube but uses a simple web interface?

**Comment by lorenzofanchi** [comment]
Hi! Thanks for providing the code for downloading from NPO. I registered at WVkeys discord and understand how to set the ENV vars, but struggling a bit to get it all running.

Could you provide a minimal example of how to run the tool, given an NPO URL to start from, e.g. `https://npo.nl/start/serie/door-het-hart-van-china/seizoen-1/`

Thanks in advance 🥇

**Comment by Ewoodss** [comment]
hey yeah so i have updated the code
downloading should work a  lot better right now,
i also create a very simple cli script. so that the code can be used from the command line.

```bash
node cli.js download https://npo.nl/start/serie/door-het-hart-van-china/seizoen-1/mijnen-en-woestijnen/afspelen
```
should download the first episode of the npo season currently don't have support working for batch full season downloading

**Comment by lorenzofanchi** [comment]
Eindbaas! It works 🥇

**Comment by Ewoodss** [comment]
I am closing this issue for now, if there's any more documentation needed or something is unclear, feel free to open a new issue.
